FROM inn0kenty/pyinstaller-alpine:3.7
WORKDIR /src
COPY . .
RUN /pyinstaller/pyinstaller.sh \
    --onefile \
    --clean \
    hello-flask.py &&\
    mkdir /output &&\
    cp /src/dist/hello-flask /output

